name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name : Setup env
        run: |
          sudo apt-get install -y jq
          echo "PACKAGE_NAME=$( cat package.json | jq -r '.name' )" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$( cat package.json | jq -r '.version' )" >> $GITHUB_ENV

      # https://github.com/actions/create-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: '${{env.PACKAGE_VERSION}}'
          release_name: 'Release ${{env.PACKAGE_NAME}} ${{env.PACKAGE_VERSION}}'
          draft: false
          prerelease: false
          owner: Subarna Karki